/** Woodenbot Card Actions */
export enum WBAction {
  CARD = 'CARD',
  CARD_RED = 'CARD_RED',
  CRYSTALS = 'CRYSTALS',
  EYE = 'EYE',
  EYE_RED = 'EYE_RED',
  WARBAND = 'WARBAND',
  WARBAND_RED = 'WARBAND_RED',
  SHIELD = 'SHIELD',
  SHIELD_RED = 'SHIELD_RED',
  ALERT = 'ALERT',
  ALERT_RED = 'ALERT_RED',
  //
  CUBES = 'CUBES',
  CUBES_RED = 'CUBES_RED',
  BATTLE = 'BATTLE',
  SEARCH = 'SEARCH',
  SEARCH_RED = 'SEARCH_RED',
  ARROWS = 'ARROWS',
}
